---
apiVersion: v1
kind: Namespace
metadata:
  name: github-runner
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: github-runner
stringData:
  token: XXX
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - github-runner
      automountServiceAccountToken: false
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      - name: dind-storage
        emptyDir: {}
      - name: dind-certs
        emptyDir: {}
      - name: dind-run
        emptyDir: {}
      - name: dind-runner
        emptyDir: {}
      containers:
      - name: dind
        image: docker:20.10.16-dind
        command:
        - /usr/local/bin/dockerd-entrypoint.sh
        - --mtu=1100
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /lib/modules
            name: modules
            readOnly: true
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - name: dind-storage
            mountPath: /var/lib/docker
          - name: dind-run
            mountPath: /var/run
          - name: dind-runner
            mountPath: /runner
      - name: github-runner
        image: quay.io/kairos/github-runner:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: VERSION
          value: "2.287.1"
        - name: KUBEHOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ORG
          value: XXX
        - name: REPO
          value: XXX
        - name: TOKEN # stored separately in a Kubernetes secret
          valueFrom:
            secretKeyRef:
              name: github-token
              key: token
        volumeMounts:
        - name: dind-run
          mountPath: /var/run
        - name: dind-runner
          mountPath: /runner